CREATE TABLE bus_report (
  id int(10) NOT NULL auto_increment,
  name varchar(255) NOT NULL default '',
  report_type tinyint(1) NOT NULL default '0',
  quantity int(5) NOT NULL default '0',
  start_date varchar(255) NOT NULL default '',
  end_date varchar(255) NOT NULL default '',
  sales_name varchar(200) DEFAULT NULL,
  print_method tinyint(1) NOT NULL default '0',
  status tinyint(2) NOT NULL default '1',
  stage tinyint(1) NOT NULL default '1',
  log text default NULL,
  memo text default NULL,
  brief varchar(255) NOT NULL default '',
  creator int(10) NOT NULL default '0',
  c_time int(10) NOT NULL default '0',
  modifier int(10) NOT NULL default '0',
  m_time int(10) NOT NULL default '0',
  PRIMARY KEY  (id),
);
